name: Mythril

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mythril:
    name: Mythril
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Python 3.10 ensures old node-gyp (from Node 12's npm) doesn't hit the Python 3.12 'rU' bug
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Yarn dependencies
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Configure npm to use Python 3.10 (for node-gyp)
        run: npm config set python "python3.10"

      - name: Install node dependencies
        run: yarn install --frozen-lockfile
        env:
          PYTHON: python3.10

      - name: Install solc 0.6.12
        run: |
          sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
          sudo chmod +x /usr/bin/solc

      - name: Flatten contracts
        run: yarn waffle flatten

      - name: Install Mythril
        run: |
          python -m pip install --upgrade pip
          pip install mythril

      - name: Run Mythril
        run: myth analyze flatten/BabylonianEchidnaTest.sol:BabylonianEchidnaTest
